lab3: lab3.c Extensiones/funciones.o
		gcc -o lab3 lab3.c Extensiones/funciones.o -Wall -lm

funciones.o: Extensiones/funciones.c
		gcc -c Extensiones/funciones.c -Wall -lm

clear:
		rm -f lab3 Extensiones/*.o